import type { Translations, PollingStation, Candidate, BallotMeasure, ElectionResult } from "./types";

export const TRANSLATIONS: Translations = {
  en: {
    appTitle: "Election Day Portal",
    appSubtitle: "Your guide to voting, results, and election info",
    login: "Sign In",
    logout: "Sign Out",
    online: "Online",
    offline: "Offline",
    pollingPlaces: "Polling Places",
    sampleBallot: "Sample Ballot",
    liveResults: "Live Results",
    workerSync: "Worker Sync",
    search: "Search polling places...",
    reportWait: "Report Wait Time",
    minutes: "min",
    yourSelection: "Your Selection",
    voterTurnout: "Voter Turnout",
    pendingSync: "Pending Sync",
    syncNow: "Sync Now",
    language: "Language",
    voterId: "Voter ID Number",
    passcode: "Passcode / PIN",
    loginTitle: "Sign In to Your Account",
    loginOnline: "Online Voter Login",
    loginOffline: "Offline Voter Login",
    loginStaff: "Staff Emergency Login",
    noResults: "No items found",
    loading: "Loading...",
    error: "Something went wrong",
    accessibility: "Accessible",
    directions: "Get Directions",
    candidate: "Candidate",
    measure: "Ballot Measure",
    vote: "Vote",
    totalVotes: "Total Votes",
    lastUpdated: "Last updated",
    offlineMode: "Offline Mode",
    onlineMode: "Online Mode",
    toggleOffline: "Simulate Offline",
    welcome: "Welcome",
    precinct: "Precinct",
    authMode: "Auth Mode",
    checkIn: "Check In",
    submitVote: "Submit Vote",
    queued: "Queued",
    synced: "Synced",
    close: "Close",
    submit: "Submit",
    cancel: "Cancel",
  },
  es: {
    appTitle: "Portal del Día de las Elecciones",
    appSubtitle: "Su guía para votar, resultados e información electoral",
    login: "Iniciar Sesión",
    logout: "Cerrar Sesión",
    online: "En línea",
    offline: "Fuera de línea",
    pollingPlaces: "Lugares de Votación",
    sampleBallot: "Boleta de Muestra",
    liveResults: "Resultados en Vivo",
    workerSync: "Sincronización de Trabajadores",
    search: "Buscar lugares de votación...",
    reportWait: "Reportar Tiempo de Espera",
    minutes: "min",
    yourSelection: "Su Selección",
    voterTurnout: "Participación Electoral",
    pendingSync: "Sincronización Pendiente",
    syncNow: "Sincronizar Ahora",
    language: "Idioma",
    voterId: "Número de Identificación del Votante",
    passcode: "Código de Acceso / PIN",
    loginTitle: "Inicie Sesión en Su Cuenta",
    loginOnline: "Inicio de Sesión en Línea",
    loginOffline: "Inicio de Sesión Fuera de Línea",
    loginStaff: "Inicio de Sesión de Emergencia para Personal",
    noResults: "No se encontraron elementos",
    loading: "Cargando...",
    error: "Algo salió mal",
    accessibility: "Accesible",
    directions: "Obtener Direcciones",
    candidate: "Candidato",
    measure: "Medida Electoral",
    vote: "Votar",
    totalVotes: "Total de Votos",
    lastUpdated: "Última actualización",
    offlineMode: "Modo Fuera de Línea",
    onlineMode: "Modo en Línea",
    toggleOffline: "Simular Modo Fuera de Línea",
    welcome: "Bienvenido",
    precinct: "Distrito Electoral",
    authMode: "Modo de Autenticación",
    checkIn: "Registrar Entrada",
    submitVote: "Enviar Voto",
    queued: "En cola",
    synced: "Sincronizado",
    close: "Cerrar",
    submit: "Enviar",
    cancel: "Cancelar",
  },
  fr: {
    appTitle: "Portail du Jour des Élections",
    appSubtitle: "Votre guide pour voter, les résultats et les infos électorales",
    login: "Connexion",
    logout: "Déconnexion",
    online: "En ligne",
    offline: "Hors ligne",
    pollingPlaces: "Lieux de Vote",
    sampleBallot: "Bulletin de Vote",
    liveResults: "Résultats en Direct",
    workerSync: "Sync des Travailleurs",
    search: "Rechercher des lieux de vote...",
    reportWait: "Signaler le Temps d'Attente",
    minutes: "min",
    yourSelection: "Votre Sélection",
    voterTurnout: "Participation Électorale",
    pendingSync: "Sync en Attente",
    syncNow: "Synchroniser",
    language: "Langue",
    voterId: "Numéro d'Identification de l'Électeur",
    passcode: "Code d'Accès / PIN",
    loginTitle: "Connectez-vous à Votre Compte",
    loginOnline: "Connexion Électeur en Ligne",
    loginOffline: "Connexion Électeur Hors Ligne",
    loginStaff: "Connexion d'Urgence du Personnel",
    noResults: "Aucun élément trouvé",
    loading: "Chargement...",
    error: "Quelque chose s'est mal passé",
    accessibility: "Accessible",
    directions: "Obtenir l'Itinéraire",
    candidate: "Candidat",
    measure: "Mesure de Vote",
    vote: "Voter",
    totalVotes: "Total des Votes",
    lastUpdated: "Dernière mise à jour",
    offlineMode: "Mode Hors Ligne",
    onlineMode: "Mode En Ligne",
    toggleOffline: "Simuler le Mode Hors Ligne",
    welcome: "Bienvenue",
    precinct: "Circonscription",
    authMode: "Mode d'Authentification",
    checkIn: "Enregistrer",
    submitVote: "Soumettre le Vote",
    queued: "En file d'attente",
    synced: "Synchronisé",
    close: "Fermer",
    submit: "Soumettre",
    cancel: "Annuler",
  },
  vi: {
    appTitle: "Cổng Thông Tin Ngày Bầu Cử",
    appSubtitle: "Hướng dẫn bỏ phiếu, kết quả và thông tin bầu cử",
    login: "Đăng Nhập",
    logout: "Đăng Xuất",
    online: "Trực tuyến",
    offline: "Ngoại tuyến",
    pollingPlaces: "Địa Điểm Bỏ Phiếu",
    sampleBallot: "Phiếu Bầu Mẫu",
    liveResults: "Kết Quả Trực Tiếp",
    workerSync: "Đồng Bộ Nhân Viên",
    search: "Tìm kiếm địa điểm bỏ phiếu...",
    reportWait: "Báo Cáo Thời Gian Chờ",
    minutes: "phút",
    yourSelection: "Lựa Chọn Của Bạn",
    voterTurnout: "Tỷ Lệ Cử Tri Đi Bầu",
    pendingSync: "Đang Chờ Đồng Bộ",
    syncNow: "Đồng Bộ Ngay",
    language: "Ngôn Ngữ",
    voterId: "Số CMND Cử Tri",
    passcode: "Mã PIN / Mật Khẩu",
    loginTitle: "Đăng Nhập Tài Khoản",
    loginOnline: "Đăng Nhập Trực Tuyến",
    loginOffline: "Đăng Nhập Ngoại Tuyến",
    loginStaff: "Đăng Nhập Khẩn Cấp Cho Nhân Viên",
    noResults: "Không tìm thấy mục nào",
    loading: "Đang tải...",
    error: "Đã xảy ra lỗi",
    accessibility: "Có thể tiếp cận",
    directions: "Chỉ Đường",
    candidate: "Ứng Cử Viên",
    measure: "Biện Pháp Bỏ Phiếu",
    vote: "Bỏ Phiếu",
    totalVotes: "Tổng Số Phiếu",
    lastUpdated: "Cập nhật lần cuối",
    offlineMode: "Chế Độ Ngoại Tuyến",
    onlineMode: "Chế Độ Trực Tuyến",
    toggleOffline: "Mô Phỏng Ngoại Tuyến",
    welcome: "Chào Mừng",
    precinct: "Khu Vực Bầu Cử",
    authMode: "Chế Độ Xác Thực",
    checkIn: "Điểm Danh",
    submitVote: "Gửi Phiếu Bầu",
    queued: "Đã xếp hàng",
    synced: "Đã đồng bộ",
    close: "Đóng",
    submit: "Gửi",
    cancel: "Hủy",
  },
  tl: {
    appTitle: "Portal ng Araw ng Eleksyon",
    appSubtitle: "Ang iyong gabay sa pagboto, resulta, at impormasyon sa eleksyon",
    login: "Mag-sign In",
    logout: "Mag-sign Out",
    online: "Online",
    offline: "Offline",
    pollingPlaces: "Mga Lugar ng Pagboto",
    sampleBallot: "Halimbawang Balota",
    liveResults: "Mga Resulta ng Live",
    workerSync: "Pag-sync ng Manggagawa",
    search: "Maghanap ng mga lugar ng pagboto...",
    reportWait: "Iulat ang Oras ng Paghihintay",
    minutes: "min",
    yourSelection: "Iyong Pagpili",
    voterTurnout: "Pagboto ng mga Botante",
    pendingSync: "Nakapending na Sync",
    syncNow: "Mag-sync Ngayon",
    language: "Wika",
    voterId: "Numero ng ID ng Botante",
    passcode: "Passcode / PIN",
    loginTitle: "Mag-sign In sa Iyong Account",
    loginOnline: "Online na Pag-login ng Botante",
    loginOffline: "Offline na Pag-login ng Botante",
    loginStaff: "Staff Emergency Login",
    noResults: "Walang nakitang mga item",
    loading: "Naglo-load...",
    error: "May maling nangyari",
    accessibility: "Naa-access",
    directions: "Kunin ang mga Direksyon",
    candidate: "Kandidato",
    measure: "Sukatan ng Balota",
    vote: "Bumoto",
    totalVotes: "Kabuuang Boto",
    lastUpdated: "Huling na-update",
    offlineMode: "Offline Mode",
    onlineMode: "Online Mode",
    toggleOffline: "Gayahin ang Offline",
    welcome: "Maligayang Pagdating",
    precinct: "Presinto",
    authMode: "Auth Mode",
    checkIn: "Mag-check In",
    submitVote: "Isumite ang Boto",
    queued: "Nakapila",
    synced: "Naka-sync",
    close: "Isara",
    submit: "Isumite",
    cancel: "Kanselahin",
  },
};

export const MOCK_PRECINCTS = [
  "Precinct 1 - Downtown",
  "Precinct 2 - Riverside",
  "Precinct 3 - Westside",
  "Precinct 4 - Eastside",
  "Precinct 5 - Northgate",
];

export const MOCK_POLLING_STATIONS: PollingStation[] = [
  { id: "p1", name: "City Hall Auditorium", address: "100 Main St, Downtown", precinct: "Precinct 1 - Downtown", waitTime: 12, accessibility: true, lat: 40.7128, lng: -74.006 },
  { id: "p2", name: "Riverside Community Center", address: "200 River Rd, Riverside", precinct: "Precinct 2 - Riverside", waitTime: 25, accessibility: true, lat: 40.7282, lng: -73.994 },
  { id: "p3", name: "Westside Library", address: "350 Oak Ave, Westside", precinct: "Precinct 3 - Westside", waitTime: 8, accessibility: true, lat: 40.7401, lng: -74.010 },
  { id: "p4", name: "Eastside High School Gym", address: "500 Elm St, Eastside", precinct: "Precinct 4 - Eastside", waitTime: 45, accessibility: false, lat: 40.7500, lng: -73.980 },
  { id: "p5", name: "Northgate Town Hall", address: "700 Pine Blvd, Northgate", precinct: "Precinct 5 - Northgate", waitTime: 18, accessibility: true, lat: 40.7600, lng: -73.970 },
];

export const MOCK_CANDIDATES: Candidate[] = [
  { id: "c1", name: "Maria Santos", party: "Progressive Alliance", office: "Mayor", description: "Former city councilor focused on affordable housing and transit.", imageUrl: "" },
  { id: "c2", name: "James Chen", party: "United Forward", office: "Mayor", description: "Business leader and philanthropist with a focus on economic growth.", imageUrl: "" },
  { id: "c3", name: "Aisha Patel", party: "Green Party", office: "Mayor", description: "Environmental attorney and community organizer.", imageUrl: "" },
  { id: "c4", name: "Robert Kim", party: "Progressive Alliance", office: "City Council District 3", description: "Incumbent councilor focused on public safety and education.", imageUrl: "" },
  { id: "c5", name: "Linda O'Brien", party: "United Forward", office: "City Council District 3", description: "Small business owner and parent advocate.", imageUrl: "" },
];

export const MOCK_BALLOT_MEASURES: BallotMeasure[] = [
  {
    id: "m1",
    title: "Proposition A: School Funding",
    description: "Shall the city increase property tax by 0.5% to fund public school improvements and teacher salaries?",
    options: [{ label: "Yes", value: "yes" }, { label: "No", value: "no" }],
  },
  {
    id: "m2",
    title: "Proposition B: Transit Expansion",
    description: "Shall the city allocate $200M for a new light rail line connecting downtown to the airport?",
    options: [{ label: "Yes", value: "yes" }, { label: "No", value: "no" }],
  },
  {
    id: "m3",
    title: "Measure C: Green Spaces",
    description: "Shall the city convert 50 acres of underutilized land into public parks and community gardens?",
    options: [{ label: "Yes", value: "yes" }, { label: "No", value: "no" }],
  },
];

export const MOCK_RESULTS: ElectionResult[] = [
  { candidateId: "c1", candidateName: "Maria Santos", party: "Progressive Alliance", voteCount: 45230, percentage: 42.5, precinct: "All Precincts" },
  { candidateId: "c2", candidateName: "James Chen", party: "United Forward", voteCount: 38910, percentage: 36.6, precinct: "All Precincts" },
  { candidateId: "c3", candidateName: "Aisha Patel", party: "Green Party", voteCount: 22230, percentage: 20.9, precinct: "All Precincts" },
  { candidateId: "c4", candidateName: "Robert Kim", party: "Progressive Alliance", voteCount: 15230, percentage: 58.2, precinct: "District 3" },
  { candidateId: "c5", candidateName: "Linda O'Brien", party: "United Forward", voteCount: 10920, percentage: 41.8, precinct: "District 3" },
];

export const MOCK_VOTER_TURNOUT = { total: 106370, eligible: 185000, percentage: 57.5 };